### ISSUE TITLE
Type validation errors in versions > v1.4.3 due to old authorization_model format

### ISSUE THREAD

**Issue by ben-mays-cs** [openfga/openfga#1668] opened 2024-06-06 18:41 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

We experienced an issue trying to upgrade OpenFGA from `v1.4.3` to `v1.5.4`. The migration runs (via docker) fine but any subsequent `Check` or `ListObject` calls returns a validation error (`type %s not found`). Notably, the `Expand` operation still recognizes the types, along with the Playground. 

```
$ fga query expand read doc:abcd
{
  "tree": {
   ... results
}

$ fga query check user:u read doc:abcd
Error: failed to check due to failed to check due to Check validation error for POST Check with body {"code":"validation_error","message":"type 'doc' not found"}
 with error code validation_error error message: type 'doc' not found
```

We're currently running on `v1.43` but have been running since `v1.12`. I noticed that the authorization model storage has changed and suspect that we have an older authorization model with explicit `type` columns and serialized `type_definition` columns. 

```
openfga=# select * from authorization_model where authorization_model_id='y';
-[ RECORD 1 ]----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
store                  | s
authorization_model_id | y
type                   |
type_definition        |
schema_version         | 1.1
serialized_protobuf    |  <protobuf serialized>

openfga=# select * from authorization_model where authorization_model_id='x';
-[ RECORD 1 ]----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
store                  | s
authorization_model_id | x
type                   | doc
type_definition        |  <protobuf serialized>
schema_version         | 1.1
serialized_protobuf    |
```

To fix this issue, I did the following:
1. Re-save the same model as a new model id "y" via `fga model write --file`
2. Update the model in postgres via: `update authorization_model set authorization_model_id='x' where authorization_model_id='y';`
3. Delete older format: `delete from authorization_model where authorization_model_id='x' and type != '';` 
4. Upgrade to v1.5.4

This resolved the issue and did not break traffic, as the model-id did not change.

I did a pass through the code and couldn't find a smoking gun, notably https://github.com/openfga/openfga/blame/main/pkg/storage/sqlcommon/sqlcommon.go#L502-L518 looks correct in that it always exits with the deserialized model iff one exists. The behavior when one doesn't exist seems sound.

This change does seem correlated with the breakage: https://github.com/openfga/openfga/pull/1387

### Expectation

I expected the older format schema to work with the newer request validation logic. This is a breaking change somewhere in >`v1.4.3`.

### Reproduction

1. Given a older row-per-type authorization_model stored in Postgres
2. Validation fails in Check/ListObject calls due to missing type information

### OpenFGA version

v1.4.3

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

No

**Comment by ben-mays-cs** [comment] 2024-06-06 18:43
I suspect this `limit: 1` in the [FindLatestAuthorizationModel](https://github.com/openfga/openfga/pull/1387/files#diff-d4415e74b94ab18e955f1b14cfd07a462889a57f9dcc3770a4ef549ee48e10e0R546) is the culprit. The older authorization models are many rows, whereas the new ones are single rows.

**Comment by rhamzeh** [comment] 2024-06-06 20:14
Sorry for that experience @ben-mays-cs, and thanks for posting your workaround - this should definitely not be the experience.

We will take a closer look at this and update you once we have anything!

**Comment by miparnisari** [comment] 2024-07-15 02:17
@jpadilla could this be caused by an incomplete migration? In https://github.com/openfga/openfga/issues/1025 i see that there are a couple releases that were never marked as complete.

**Comment by miparnisari** [comment] 2024-10-01 19:44
@ben-mays-cs sorry for taking so long to get to this! Thanks for posting a potential root cause in [your comment](https://github.com/openfga/openfga/issues/1668#issuecomment-2153173449) 🙇‍♀️. Could you please test https://github.com/openfga/openfga/pull/1980 via `go get -u github.com/openfga/openfga@fix-1668` and let me know whether this solves the problem?

**Closed** 2024-10-01 20:56 UTC
Labels: bug
