### ISSUE TITLE
Severe Performance Penalty as tuples grow

### ISSUE THREAD

**Issue by ghstahl** [openfga/openfga#727] opened 2023-05-07 15:00 UTC
[for-openfga.zip](https://github.com/openfga/openfga/files/11415294/for-openfga.zip)
[1.0.1](https://github.com/openfga/openfga/releases/tag/v1.0.1)  running in docker for the tests.  

My model, loosely based upon github orgs and users, has a severe performance penalty as the number of tuples grow.  

An org has users, roles, plans, and permissions etc.  ( about 62 tuples )

When there is one org, my checks for both ```true``` and ```false``` response come in at 5ms.
True checks are fairly constant as tuples grow.  
False checks climb to 3 to 5s with an occasional deadline exceeded error.  

I have attached my load test app.
It only requires that there be no store named "mapped".  It creates one with my authorization model.

From the log below you can see what happens in ```100``` org increments.  
There are ```5K``` orgs.

```console
{"level":"info","org_index":0,"duration":8.7006,"time":"2023-05-07T07:49:05-07:00","message":"Check = true"}
{"level":"info","org_index":0,"duration":3.9996,"time":"2023-05-07T07:49:05-07:00","message":"Check = false"}
{"level":"info","org_index":100,"duration":104.8947,"time":"2023-05-07T07:49:12-07:00","message":"Check = true"}
{"level":"info","org_index":100,"duration":129.3856,"time":"2023-05-07T07:49:12-07:00","message":"Check = false"}
{"level":"info","org_index":200,"duration":119.8455,"time":"2023-05-07T07:49:19-07:00","message":"Check = true"}
{"level":"info","org_index":200,"duration":190.3305,"time":"2023-05-07T07:49:19-07:00","message":"Check = false"}
{"level":"info","org_index":300,"duration":165.0575,"time":"2023-05-07T07:49:27-07:00","message":"Check = true"}
{"level":"info","org_index":300,"duration":290.5505,"time":"2023-05-07T07:49:27-07:00","message":"Check = false"}
{"level":"info","org_index":400,"duration":339.1564,"time":"2023-05-07T07:49:34-07:00","message":"Check = true"}
{"level":"info","org_index":400,"duration":363.411,"time":"2023-05-07T07:49:35-07:00","message":"Check = false"}
{"level":"info","org_index":500,"duration":395.8813,"time":"2023-05-07T07:49:42-07:00","message":"Check = true"}
{"level":"info","org_index":500,"duration":415.2293,"time":"2023-05-07T07:49:43-07:00","message":"Check = false"}
{"level":"info","org_index":600,"duration":222.3836,"time":"2023-05-07T07:49:50-07:00","message":"Check = true"}
{"level":"info","org_index":600,"duration":371.8665,"time":"2023-05-07T07:49:50-07:00","message":"Check = false"}
{"level":"info","org_index":700,"duration":430.2643,"time":"2023-05-07T07:49:58-07:00","message":"Check = true"}
{"level":"info","org_index":700,"duration":500.8352,"time":"2023-05-07T07:49:59-07:00","message":"Check = false"}
{"level":"info","org_index":800,"duration":139.0281,"time":"2023-05-07T07:50:06-07:00","message":"Check = true"}
{"level":"info","org_index":800,"duration":512.1669,"time":"2023-05-07T07:50:06-07:00","message":"Check = false"}
{"level":"info","org_index":900,"duration":299.6228,"time":"2023-05-07T07:50:14-07:00","message":"Check = true"}
{"level":"info","org_index":900,"duration":699.5794,"time":"2023-05-07T07:50:14-07:00","message":"Check = false"}
{"level":"info","org_index":1000,"duration":182.5979,"time":"2023-05-07T07:50:21-07:00","message":"Check = true"}
{"level":"info","org_index":1000,"duration":656.7759,"time":"2023-05-07T07:50:22-07:00","message":"Check = false"}
{"level":"info","org_index":1100,"duration":223.3459,"time":"2023-05-07T07:50:29-07:00","message":"Check = true"}
{"level":"info","org_index":1100,"duration":673.0305,"time":"2023-05-07T07:50:30-07:00","message":"Check = false"}
{"level":"info","org_index":1200,"duration":407.3561,"time":"2023-05-07T07:50:38-07:00","message":"Check = true"}
{"level":"info","org_index":1200,"duration":877.5191,"time":"2023-05-07T07:50:39-07:00","message":"Check = false"}
{"level":"info","org_index":1300,"duration":174.7522,"time":"2023-05-07T07:50:46-07:00","message":"Check = true"}
{"level":"info","org_index":1300,"duration":737.248,"time":"2023-05-07T07:50:47-07:00","message":"Check = false"}
{"level":"info","org_index":1400,"duration":566.0231,"time":"2023-05-07T07:50:55-07:00","message":"Check = true"}
{"level":"info","org_index":1400,"duration":998.9711,"time":"2023-05-07T07:50:56-07:00","message":"Check = false"}
{"level":"info","org_index":1500,"duration":483.9359,"time":"2023-05-07T07:51:03-07:00","message":"Check = true"}
{"level":"info","org_index":1500,"duration":1178.0642,"time":"2023-05-07T07:51:05-07:00","message":"Check = false"}
{"level":"info","org_index":1600,"duration":189.069,"time":"2023-05-07T07:51:12-07:00","message":"Check = true"}
{"level":"info","org_index":1600,"duration":942.8202,"time":"2023-05-07T07:51:13-07:00","message":"Check = false"}
{"level":"info","org_index":1700,"duration":365.4995,"time":"2023-05-07T07:51:20-07:00","message":"Check = true"}
{"level":"info","org_index":1700,"duration":987.71,"time":"2023-05-07T07:51:21-07:00","message":"Check = false"}
{"level":"info","org_index":1800,"duration":163.1791,"time":"2023-05-07T07:51:28-07:00","message":"Check = true"}
{"level":"info","org_index":1800,"duration":1006.8545,"time":"2023-05-07T07:51:29-07:00","message":"Check = false"}
{"level":"info","org_index":1900,"duration":210.7036,"time":"2023-05-07T07:51:36-07:00","message":"Check = true"}
{"level":"info","org_index":1900,"duration":1063.5109,"time":"2023-05-07T07:51:38-07:00","message":"Check = false"}
{"level":"info","org_index":2000,"duration":439.821,"time":"2023-05-07T07:51:45-07:00","message":"Check = true"}
{"level":"info","org_index":2000,"duration":990.1202,"time":"2023-05-07T07:51:46-07:00","message":"Check = false"}
{"level":"info","org_index":2100,"duration":164.9772,"time":"2023-05-07T07:51:53-07:00","message":"Check = true"}
{"level":"info","org_index":2100,"duration":1105.833,"time":"2023-05-07T07:51:55-07:00","message":"Check = false"}
{"level":"info","org_index":2200,"duration":229.0395,"time":"2023-05-07T07:52:02-07:00","message":"Check = true"}
{"level":"info","org_index":2200,"duration":1434.9201,"time":"2023-05-07T07:52:03-07:00","message":"Check = false"}
{"level":"info","org_index":2300,"duration":198.7435,"time":"2023-05-07T07:52:11-07:00","message":"Check = true"}
{"level":"info","org_index":2300,"duration":1378.3565,"time":"2023-05-07T07:52:12-07:00","message":"Check = false"}
{"level":"info","org_index":2400,"duration":276.8651,"time":"2023-05-07T07:52:20-07:00","message":"Check = true"}
{"level":"info","org_index":2400,"duration":1412.217,"time":"2023-05-07T07:52:21-07:00","message":"Check = false"}
{"level":"info","org_index":2500,"duration":249.7963,"time":"2023-05-07T07:52:28-07:00","message":"Check = true"}
{"level":"info","org_index":2500,"duration":1294.4872,"time":"2023-05-07T07:52:29-07:00","message":"Check = false"}
{"level":"info","org_index":2600,"duration":207.1492,"time":"2023-05-07T07:52:37-07:00","message":"Check = true"}
{"level":"info","org_index":2600,"duration":1888.2477,"time":"2023-05-07T07:52:39-07:00","message":"Check = false"}
{"level":"info","org_index":2700,"duration":383.9745,"time":"2023-05-07T07:52:46-07:00","message":"Check = true"}
{"level":"info","org_index":2700,"duration":1426.3479,"time":"2023-05-07T07:52:47-07:00","message":"Check = false"}
{"level":"info","org_index":2800,"duration":220.5924,"time":"2023-05-07T07:52:55-07:00","message":"Check = true"}
{"level":"info","org_index":2800,"duration":1450.4985,"time":"2023-05-07T07:52:56-07:00","message":"Check = false"}
{"level":"info","org_index":2900,"duration":322.7839,"time":"2023-05-07T07:53:03-07:00","message":"Check = true"}
{"level":"info","org_index":2900,"duration":1993.6173,"time":"2023-05-07T07:53:05-07:00","message":"Check = false"}
{"level":"info","org_index":3000,"duration":324.7837,"time":"2023-05-07T07:53:13-07:00","message":"Check = true"}
{"level":"info","org_index":3000,"duration":1669.222,"time":"2023-05-07T07:53:14-07:00","message":"Check = false"}
{"level":"info","org_index":3100,"duration":243.6217,"time":"2023-05-07T07:53:22-07:00","message":"Check = true"}
{"level":"info","org_index":3100,"duration":1849.3523,"time":"2023-05-07T07:53:23-07:00","message":"Check = false"}
{"level":"info","org_index":3200,"duration":277.6591,"time":"2023-05-07T07:53:31-07:00","message":"Check = true"}
{"level":"info","org_index":3200,"duration":1897.7956,"time":"2023-05-07T07:53:33-07:00","message":"Check = false"}
{"level":"info","org_index":3300,"duration":300.1656,"time":"2023-05-07T07:53:40-07:00","message":"Check = true"}
{"level":"info","org_index":3300,"duration":2408.1394,"time":"2023-05-07T07:53:42-07:00","message":"Check = false"}
{"level":"info","org_index":3400,"duration":341.8782,"time":"2023-05-07T07:53:50-07:00","message":"Check = true"}
{"level":"info","org_index":3400,"duration":2076.6788,"time":"2023-05-07T07:53:52-07:00","message":"Check = false"}
{"level":"info","org_index":3500,"duration":396.227,"time":"2023-05-07T07:53:59-07:00","message":"Check = true"}
{"level":"info","org_index":3500,"duration":1829.9855,"time":"2023-05-07T07:54:01-07:00","message":"Check = false"}
{"level":"info","org_index":3600,"duration":247.2554,"time":"2023-05-07T07:54:08-07:00","message":"Check = true"}
{"level":"info","org_index":3600,"duration":1836.7453,"time":"2023-05-07T07:54:10-07:00","message":"Check = false"}
{"level":"info","org_index":3700,"duration":322.2409,"time":"2023-05-07T07:54:18-07:00","message":"Check = true"}
{"level":"info","org_index":3700,"duration":2115.8193,"time":"2023-05-07T07:54:20-07:00","message":"Check = false"}
{"level":"info","org_index":3800,"duration":430.1194,"time":"2023-05-07T07:54:27-07:00","message":"Check = true"}
{"level":"info","org_index":3800,"duration":2244.4073,"time":"2023-05-07T07:54:29-07:00","message":"Check = false"}
{"level":"info","org_index":3900,"duration":413.5122,"time":"2023-05-07T07:54:37-07:00","message":"Check = true"}
{"level":"info","org_index":3900,"duration":2514.885,"time":"2023-05-07T07:54:39-07:00","message":"Check = false"}
{"level":"info","org_index":4000,"duration":375.5794,"time":"2023-05-07T07:54:47-07:00","message":"Check = true"}
{"level":"info","org_index":4000,"duration":2102.3139,"time":"2023-05-07T07:54:49-07:00","message":"Check = false"}
{"level":"info","org_index":4100,"duration":331.9491,"time":"2023-05-07T07:54:56-07:00","message":"Check = true"}
{"level":"info","org_index":4100,"duration":2124.326,"time":"2023-05-07T07:54:58-07:00","message":"Check = false"}
{"level":"info","org_index":4200,"duration":322.9402,"time":"2023-05-07T07:55:06-07:00","message":"Check = true"}
{"level":"info","org_index":4200,"duration":2221.9674,"time":"2023-05-07T07:55:08-07:00","message":"Check = false"}
{"level":"info","org_index":4300,"duration":269.4642,"time":"2023-05-07T07:55:15-07:00","message":"Check = true"}
{"level":"info","org_index":4300,"duration":1935.2659,"time":"2023-05-07T07:55:17-07:00","message":"Check = false"}
{"level":"info","org_index":4400,"duration":292.4552,"time":"2023-05-07T07:55:25-07:00","message":"Check = true"}
{"level":"info","org_index":4400,"duration":2328.2129,"time":"2023-05-07T07:55:27-07:00","message":"Check = false"}
{"level":"info","org_index":4500,"duration":264.9108,"time":"2023-05-07T07:55:34-07:00","message":"Check = true"}
{"level":"info","org_index":4500,"duration":2105.3159,"time":"2023-05-07T07:55:36-07:00","message":"Check = false"}
{"level":"info","org_index":4600,"duration":245.7864,"time":"2023-05-07T07:55:43-07:00","message":"Check = true"}
{"level":"info","org_index":4600,"duration":2415.0218,"time":"2023-05-07T07:55:46-07:00","message":"Check = false"}
{"level":"info","org_index":4700,"duration":310.0797,"time":"2023-05-07T07:55:53-07:00","message":"Check = true"}
{"level":"info","org_index":4700,"duration":2201.4775,"time":"2023-05-07T07:55:55-07:00","message":"Check = false"}
{"level":"info","org_index":4800,"duration":252.8862,"time":"2023-05-07T07:56:02-07:00","message":"Check = true"}
{"level":"info","org_index":4800,"duration":2285.4782,"time":"2023-05-07T07:56:05-07:00","message":"Check = false"}
{"level":"info","org_index":4900,"duration":332.1747,"time":"2023-05-07T07:56:12-07:00","message":"Check = true"}
{"level":"info","org_index":4900,"duration":2802.5699,"time":"2023-05-07T07:56:15-07:00","message":"Check = false"}
{"level":"info","duration":300.1595,"time":"2023-05-07T07:56:22-07:00","message":"Check = true"}
{"level":"info","duration":2561.9071,"time":"2023-05-07T07:56:25-07:00","message":"Check = false"}
```

**Comment by aaguiarz** [comment] 2023-05-07 15:58
Thanks @ghstahl, just to confirm, are you using the Postgres storage adapter?

**Comment by ghstahl** [comment] 2023-05-07 16:36
Yes, Postgres.
```yaml
datastore:
  engine: postgres
  uri: postgres://postgres:password@postgresql:5432/openfga
authn:
  method: preshared
  preshared:
    keys: ["key1", "key2"]
```

this is my docker entry.
```yaml
  postgresql:
    <<: *default-service
    container_name: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./config/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
```

**Comment by jon-whit** [comment] 2023-05-08 15:32
@ghstahl taking a look into this 👍

**Comment by jon-whit** [comment] 2023-05-08 21:23
@ghstahl I've pruned the model and relationship tuples down to a minimally working set that demonstrates the original issue. Here is the pruned model and relationship tuples that still demonstrate the problem.

```
model
  schema 1.1

type user

type permission
  relations
    define access: member from associated_role
    define associated_role: [role]

type role
  relations
    define associated_role_group: [role_group]
    define member: member from associated_role_group

type role_group
  relations
    define member: [user]
```

|   | object                                    | relation              | user                               |
|---|-------------------------------------------|-----------------------|------------------------------------|
| 1 | permission:destination.connector.org.read | associated_role       | role:admin                         |
| 2 | role:admin                                | associated_role_group | role_group:org.{{org_index}}/admin |
| 3 | role_group:org.{{org_index}}/admin        | member                | user:org.{{org_index}}.user.0      |

Observations:
* The only reason `user:org.0.user.0` has the `permission:destination.connector.org.read#access` relationship is because of the direct `role_group:org.0/admin#member` relationship (tuple # 3). If you remove this tuple then `user:org.0.user.0` no longer has the relationship.
* The number of `role:admin#associated_role_group` relationships increase as you increase the number of organizations in the system. **This is the primary source of the degrading performance.**

Consider N to be the number of organizations in the system. With a large number of N you will have a large number of relationships of this form:

| object     | relation              | user                   |
|------------|-----------------------|------------------------|
| role:admin | associated_role_group | role_group:org.1/admin |
| ...        | ...                   | ...                    |
| role:admin | associated_role_group | role_group:org.N/admin |

Consequently, when evaluating the `role:admin#member` relationship, you will have to evaluate N relationships of the form `role_group:org.<X>/admin#member`, and this gets more costly the larger N is. This is because evaluating `X from Y` in a relationship definition requires lookup of the `Y` relationship (which can yield multiple objects) followed by the evaluation of the `X` relationship on each one of the objects found for `Y`. Given that `user:org.0.user.0` has a direct `role_group:org.0/admin#member` relationship, that evaluation path quickly short circuits and so evaluation of the N other relationships is unecessary (thus the performance doesn't degrade linearly with lager values of N). However, for `user:org.0.user.1` it cannot be proven that they do not have access until all N `role_group#member` relationships have been evaluated, and this is why performance gets worse for increasingly larger values of N.

I'll try to come up with a model that achieves the same functionality, but without this side-effect. Give me some time to further analyze and assess some modeling recommendations. In the meantime, if you think of anything feel free to update.

**Comment by ghstahl** [comment] 2023-05-08 21:57
I was trying to have a single role where I could add permissions in one place and every org would get it.  
i.e. add a new permission to the role:admin object.  

if I made the role unique.  i.e. role:{{org_id}}/admin vs as singleton role:admin, then it looks like I will get the performance I want.  The issue then would be what do I do if I want to update what permissions a role had.  So for 5K orgs I would have to updated all of them.

I would make that trade if there is no other choice.

**Comment by ghstahl** [comment] 2023-05-08 22:56
I think the problem is all the way down at the permission object.
does user:anne have access to permission:readwrite.
permission:readwrite is singular and has a relationship to every role:{{org_id}}/admin (5K of them}}

The high level model is supposed to do this. 

a ```user``` only has a ```permission``` if they are in a ```role_group``` that carries that ```permission``` **AND**
the ```org``` has a ```plan``` that has a ```feature``` that has that same ```permission```.

So if there is a permission called ```permission:storage.read```, it has to be first in a feature called ```storage```.  The storage feature must be part of a plan which the org subscribes to.   Just because the org bought the plan, doesn't mean a user gets to use it.
The user has to be in a role_group that also carries that permission.  

I think that this would become unmanageable if my permissions aren't singular, as well as features, etc.

**Comment by ghstahl** [comment] 2023-05-09 13:50
Let me know if I have found myself in this situation: https://openfga.dev/docs/interacting/search-with-permissions
A top-down traversal of the graph where the user_id would get a false answer would find it pretty quickly vs the bottom up traversal starting from the permission. 

I am starting to wonder if I need a shadow graph that has flattened the user/org/permission relationship after taking into account all the other constraints (plans, features) that the org has subscribed to.

My checks into that flattened user/org/permission graph would be very fast and would only have to be updated on change (user added to a role_group and an orgs plan/feature change).

**Comment by mpereira-ae** [comment] 2023-07-05 00:51
For the record, I am also experiencing "context deadline exceeded" in false checks with a similar model.

**Comment by RichardAkman** [comment] 2023-09-19 09:50
We are also dealing with the same type of issue. We also use the Postgres storage adapter in the environment we see this issue. We consistently encounter the `occasional deadline exceeded` error whenever the `check` for `config-set` we perform should return a `false` response. Any `true` answer takes a few seconds. We didn't encounter any such issue during local development even though we performed stress testing with above 100k tuples.

Here is our model:
```
model
  schema 1.1
type user
type token
type role
  relations
    define assignee: [user,token]
type org
  relations
    define manage_member: [role#assignee]
    define manage_role: [role#assignee]
    define manage_token: [role#assignee]
    define manage_webhook: [role#assignee]
    define edit_settings: [role#assignee]
    define transfer_ownership: [role#assignee]
    define delete_org: [role#assignee]
type config-set
  relations
    define child: [config-set]
    define parent: [config-set]
    define read: [role#assignee] or write or read from child or read_all
    define read_all: [role#assignee] or read_all from parent or write_all
    define write: [role#assignee] or write from parent or write_all
    define write_all: [role#assignee] or write_all from parent
```

In our environment, there are a few hundred organizations, and each org starts with 17 tuples. Which means that there are between 10k to 20k tuples.

Is there some way to analyze why the `occasional deadline exceeded` error occurs?

**Comment by miparnisari** [comment] 2023-10-18 00:02
Hi @RichardAkman, sorry for not responding earlier, I just saw your comment. If you are still seeing `deadline exceeded` errors, can you please open a new issue?

**Comment by jon-whit** [comment] 2023-10-23 20:24
> For the record, I am also experiencing "context deadline exceeded" in false checks with a similar model, but with far fewer tuples. 9 tuples, to be precise.

@mpereira-ae can you still produce on the latest release of OpenFGA (`v1.3.3`)? If so, do you mind providing a reproducible example for us to test?

* What version of OpenFGA?
* What settings were provided to OpenFGA?
    * Database connection settings?
    * Max concurrent reads for Check?
    * Resolve node breadth limit?
* Model, tuples, and Check queries being called?

**Comment by miparnisari** [comment] 2024-01-09 22:59
@ghstahl @mpereira-ae @RichardAkman i'm going to close this issue, since it has become stale. If you are still experiencing performance issues, please open a new one. Thank you!

**Comment by miparnisari** [comment] 2024-01-09 22:59
closing

**Closed by miparnisari** 2024-01-09 22:59 UTC
Labels: performance
