### ISSUE TITLE
/check endpoint for list of relations

### ISSUE THREAD

**Issue by psadovsky** [openfga/openfga#470] opened 2023-01-25 10:24 UTC
Currently, if we want to check multiple relations at once, we have to call parallelly /check endpoint. The problem is that we have to send multiple requests for something that could be done by one. It would be great if there is some endpoint for evaluating multiple relations.

**Comment by rhamzeh** [comment] 2023-01-25 15:16
Thanks for your request @psadovsky

We are planning on making this part of our SDKs first before making it a server side API endpoint.

That is for several reasons, some of which include:
1. It allows us to support this faster without having to expand the API surface
2. It allows us to get feedback and use-cases before settling on an interface we cannot break without an API backward incompatible change
3. Ideally, the check requests should go to multiple servers so as not to overload one. We don't currently have server request dispatching where one server would delegate to others, but even then, it would be doing roughly the same thing

The SDK implementation ticket is being tracked here: https://github.com/openfga/sdk-generator/issues/23

There is also another issue here tracking Batch Check: https://github.com/openfga/openfga/issues/182

I will close this as a duplicate of it, but please feel free to upvote the original and add your use-cases/idea to it.

**Closed by rhamzeh** 2023-01-25 15:16 UTC
Labels: duplicate, enhancement
