### ISSUE TITLE
bug: open fga crashes for no apparent reason

### ISSUE THREAD

**Issue by tnipri** [openfga/openfga#176] opened 2022-08-17 20:59 UTC
Hey,

I'm using open fga using docker (I'm using the latest version - 0.2.0). The docker works fine, but after some time - sending a request to openfga (using SDK) returns a 500 error with the following message:
`"FGA API Internal Error: post check : Error Internal Server Error"`

Logs from docker container:
`2022-08-17T20:55:47.861Z        ERROR   grpc error      {"error": "rpc error: code = Unknown desc = rpc error: code = Code(4000) desc = Internal Server Error", "request_url": "/stores/01G9TE715A51EDP84Q7S9VH9CX/check"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server.New.func1
        /home/runner/work/openfga/openfga/server/server.go:143
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.HTTPError
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/errors.go:81
go.buf.build/openfga/go/openfga/api/openfga/v1.RegisterOpenFGAServiceHandlerClient.func3
        /home/runner/go/pkg/mod/go.buf.build/openfga/go/openfga/api@v1.2.27/openfga/v1/openfga_service.pb.gw.go:1591
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/mux.go:386
github.com/rs/cors.(*Cors).Handler.func1
        /home/runner/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231
net/http.HandlerFunc.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2084
net/http.serverHandler.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2916
net/http.(*conn).serve
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:1966
`

I can't seem to reproduce it. The only thing that solves this is restarting the docker container.

**Comment by elbuo8** [comment] 2022-08-17 21:14
Could you share the request payload?

**Comment by jon-whit** [comment] 2022-08-24 23:48
@tnipri Ill dig into this more tomorrow and try to reproduce. Could you at least share the model and the relationship tuples that you produce the issue with? That would help a lot.

**Comment by miparnisari** [comment] 2022-08-27 00:08
Also, what storage are you using? `memory` or `postgres`?

**Comment by tnipri** [comment] 2022-08-27 02:45
Thanks @jon-whit. Here is the model as taken from openfga playground:

type organization
  relations
    define can_change_owner as owner
    define can_delete_organization as owner
    define can_delete_user as owner
    define can_invite_user as owner
    define can_read as owner or member
    define can_read_members as owner or member
    define member as self or owner
    define owner as self

type user
  relations
    define can_read as owner or member from parent_organization
    define owner as self
    define parent_organization as self


@miparnisari - I'm using postgres. I used the migration tool from ver 0.1.7 to initialize the pg database

**Comment by tnipri** [comment] 2022-08-27 03:01
@jon-whit forgot to add the relation tuples. It's super basic:

user: user:9
relation: owner
object: organization:14

user: organization:14
relation: parent_organization
object: user:9

**Comment by jon-whit** [comment] 2022-08-28 17:30
@tnipri Using `v0.0.2` of the Javascript `@openfga/sdk` and with the authorization model and tuples above, I cannot reproduce on `v0.2.0` of the OpenFGA server.

To further troubleshoot the issue you are seeing, would you please provide a video screen capture using QuickTime or something similar to demonstrate the issue you are seeing?

Additionally, what OS and version of the OS are you running? What docker client version are you using? Any other environmental context would help us troubleshoot the issue.

**Comment by miparnisari** [comment] 2022-08-31 17:36
@tnipri would you mind pulling the latest version of the Docker image? It should log more details about the internal server error. Thank you!

**Comment by OysteinVesth** [comment] 2022-09-09 06:00
We are experiencing the exact same issue using this image `openfga/openfga:v0.2.1`. It works for a while then suddenly stops, I can make it start again by calling the `/stores` endpoint a few times. I think I actually got an `Deadline passed` message from the server, but have to wait until the next time it fails to be sure.

From the logs:
```bash
2022-09-09T05:38:22.065Z        INFO    db_stats        {"method": "ListStores", "reads": 1, "writes": 0}
2022-09-09T05:38:25.068Z        ERROR   grpc_error      {"error": "rpc error: code = Unknown desc = rpc error: code = Code(4000) desc = Internal Server Error", "request_url": "/stores"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server.New.func1
        /home/runner/work/openfga/openfga/server/server.go:143
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.HTTPError
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/errors.go:81
go.buf.build/openfga/go/openfga/api/openfga/v1.RegisterOpenFGAServiceHandlerClient.func15
        /home/runner/go/pkg/mod/go.buf.build/openfga/go/openfga/api@v1.2.28/openfga/v1/openfga_service.pb.gw.go:1843
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/mux.go:386
github.com/rs/cors.(*Cors).Handler.func1
        /home/runner/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231
net/http.HandlerFunc.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2084
net/http.serverHandler.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2916
net/http.(*conn).serve
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:1966
```

**Comment by craigpastro** [comment] 2022-09-10 01:46
Hi @OysteinVesth ! Thanks for the report. We had a bug where we were not properly logging the internal errors so it is quite difficult to figure out what is going on. A [fix](https://github.com/openfga/openfga/pull/222) has been merged to main today, and we'll try to cut a new release soon. If it is possible to use main then that may help to track down what is happening.

What this sounds like (and looks like from the error, but really it could be anything) is that OpenFGA is losing its connection to Postgres, then reconnecting. Is that possible?

**Comment by OysteinVesth** [comment] 2022-09-10 07:35
Thanks for the response @craigpastro! We are using Aurora serverless for our postgres db, so that is probably the case. 
Is this expected behavior? Is there any way we can mitigate it?

**Comment by craigpastro** [comment] 2022-09-11 18:10
Hi again @OysteinVesth. So a couple of us were able to reproduce this behaviour using serverless Aurora. Thanks again for bringing it to our attention.

I did some reading and what I think is happening is that after OpenFGA does something it will return the connection to the pool. After some time Aurora will close the connection, then when OpenFGA tries to use that connection again it ends up with a broken pipe error. pgx does not check whether the connection is dead at this point https://github.com/jackc/pgx/issues/74, hence the error. After it gets the error back it knows the connection is bad and can remove it from the pool. So the next request should work. At least that was my experience. Note pgx does not retry.

Possible mitigations:
- Upgrade to pgx v5 which calls `CheckConn()` on idle connections. v5 is in beta with an expected release this month (September). https://github.com/jackc/pgx/blob/v5-dev/CHANGELOG.md I've tried it out and so far cannot reproduce the error.
- Wrap each read in a transaction which has retries: https://github.com/jackc/pgx/issues/74. I'm not sure if that will affect performance. Haven't tried this yet.
- In Postgres, set the max connection lifetime to be shorter than the time that Aurora closes the connection. This can be done by adding, for example, `?pool_max_conn_lifetime=5m&pool_max_conn_lifetime_jitter=1m` to the connection string. I've tried this and so far can't reproduce the error.

The last one is something you can try immediately. The first two will require an update to OpenFGA.

I'll be back if I think of anything else.

**Comment by tnipri** [comment] 2022-09-12 14:14
Hey @miparnisari and @jon-whit , sorry for the delay - this issue happens randomly. I upgraded to 0.2.1 like you asked:

`starting openfga service...  {"version": "v0.2.1", "date": "2022-08-31T01:31:16Z", "commit": "2dfe665dbd8889c138cfa75c13b960d06e535876", "go-version": "go1.18.5"}`

The logs from the crash looks similar to the previous one:

`2022-09-12T13:43:32.155Z        INFO    db_stats        {"method": "Check", "reads": 10, "writes": 0}
2022-09-12T13:59:02.517Z        ERROR   grpc_error      {"error": "rpc error: code = Unknown desc = rpc error: code = Code(4000) desc = Internal Server Error", "request_url": "/stores/01G9TE715A51EDP84Q7S9VH9CX/check"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server.New.func1
        /home/runner/work/openfga/openfga/server/server.go:143
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.HTTPError
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/errors.go:81
go.buf.build/openfga/go/openfga/api/openfga/v1.RegisterOpenFGAServiceHandlerClient.func3
        /home/runner/go/pkg/mod/go.buf.build/openfga/go/openfga/api@v1.2.28/openfga/v1/openfga_service.pb.gw.go:1591
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.11.2/runtime/mux.go:386
github.com/rs/cors.(*Cors).Handler.func1
        /home/runner/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231
net/http.HandlerFunc.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2084
net/http.serverHandler.ServeHTTP
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2916
net/http.(*conn).serve
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:1966
`

Please let me know if anything else is needed.

**Comment by craigpastro** [comment] 2022-09-12 23:18
Hi @tnipri ! Sorry about that, but I think the logs we have in 0.2.1 are not sufficient to see what exactly the problem is. Are you able to run the main branch where we have improved logging? If not we are planning a new release in the very near future.

In the meantime can you give me a bit more detail about how you are running OpenFGA. In particular, how are you running Postgres and what version are you running?

And, just so I understand correctly, you start OpenFGA and it runs fine for a little while.
1. Then, after an idle period, you send a request which results in an internal server error? Or does it just happen with no idle period?
2. After you get the first internal server error do all subsequent requests also fail? And the only way to get it working again is to restart OpenFGA?

Thank you for your help!

**Comment by OysteinVesth** [comment] 2022-09-13 07:12
I might look into the last one @craigpastro.
The problem kind of fixed itself. I had forgot to add readiness/liveness probes to the OpenFGA pod. These ping the postgres db, so now it never reaches the 10 min `auto_pause` limit we've set in Aurora.

Anyway, thanks you so much for the detailed response!

**Comment by tnipri** [comment] 2022-09-13 20:33
> Hi @tnipri ! Sorry about that, but I think the logs we have in 0.2.1 are not sufficient to see what exactly the problem is. Are you able to run the main branch where we have improved logging? If not we are planning a new release in the very near future.
> 
> In the meantime can you give me a bit more detail about how you are running OpenFGA. In particular, how are you running Postgres and what version are you running?
> 
> And, just so I understand correctly, you start OpenFGA and it runs fine for a little while.
> 
> 1. Then, after an idle period, you send a request which results in an internal server error? Or does it just happen with no idle period?
> 2. After you get the first internal server error do all subsequent requests also fail? And the only way to get it working again is to restart OpenFGA?
> 
> Thank you for your help!

I'm deploying openfga using docker, so I have to wait for a new version to give more accurate logs

I'm using postgres latest version (14), also deployed using docker.

1. It suddenly happens after an idle period.
2. All subsequent requests also fail. You are correct - only by restarting I can get it working again

Let me know if you need anything else!

**Comment by craigpastro** [comment] 2022-09-14 17:53
Hi @tnipri ! I tried to replicate this by running Postgres:14 in a container with
```
$ docker run -d --name postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password postgres:14
```
then running OpenFGA from the binary so I could get the new logs, but so far with no luck. Is there anything else you could add about your setup that would help? Sorry for asking so much.

Hopefully, we will cut a new release today, so if you could try that again after and report back that would be great!

Thanks!

**Comment by tnipri** [comment] 2022-09-25 10:37
Hey @craigpastro , I don't know what's causing this issue. I updated the version and here are the new logs (it happened again):

```
2022-09-25T09:58:51.819Z        ERROR   grpc_error      {"error": "postgres error: write failed: write tcp 192.168.0.4:57202->192.168.65.2:5432: write: broken pipe", "public_error": "rpc error: code = Code(4000) desc = Internal Server Error"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).Error
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:56
github.com/openfga/openfga/server/middleware.NewErrorLoggingInterceptor.func1
        /home/runner/work/openfga/openfga/server/middleware/logging.go:20
google.golang.org/grpc.chainUnaryInterceptors.func1.1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1135
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47
google.golang.org/grpc.chainUnaryInterceptors.func1.1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1138
github.com/grpc-ecosystem/go-grpc-middleware/validator.UnaryServerInterceptor.func1
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/validator/validator.go:47
google.golang.org/grpc.chainUnaryInterceptors.func1.1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1138
google.golang.org/grpc.chainUnaryInterceptors.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1140
go.buf.build/openfga/go/openfga/api/openfga/v1._OpenFGAService_Check_Handler
        /home/runner/go/pkg/mod/go.buf.build/openfga/go/openfga/api@v1.2.30/openfga/v1/openfga_service_grpc.pb.go:377
google.golang.org/grpc.(*Server).processUnaryRPC
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301
google.golang.org/grpc.(*Server).handleStream
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938
```

**Comment by craigpastro** [comment] 2022-09-25 18:04
Hi @tnipri. This is very helpful! It seems like you are expenriencing the same problem as @OysteinVesth did above. One thing that you can try is, in your Postgres connection string, set the max connection lifetime to be quite short. Perhaps 5 minutes or so. You can do this by adding `?pool_max_conn_lifetime=5m&pool_max_conn_lifetime_jitter=1m` to your connection string.

Alternatively, now that pgx v5 has been released we could also update that library, which I think also fixes the problem.

**Comment by craigpastro** [comment] 2022-10-06 18:26
Hi again @tnipri ! Are you still seeing crashes? We released v0.2.3 today https://github.com/openfga/openfga/releases/tag/v0.2.3, which updates the pgx library to v5 which may be a fix for the bug you are seeing. If you get a chance to run it, please let us know if it solved your problem. Thanks!

**Comment by tnipri** [comment] 2022-10-12 09:44
thanks @craigpastro I've been running the new version for couple of days now - so far without exceptions!

I will post here in case I encounter anything else. Thanks again for this tool!

**Comment by craigpastro** [comment] 2022-10-12 15:01
Hi @tnipri, that’s great to hear. Seems like upgrading to pgx fixed the problem. Thank you for bringing it to our attention!

I’ll close this issue for now, but please reopen it if you encounter it again. Thanks!

**Closed by craigpastro** 2022-10-12 15:01 UTC
Labels: bug

**Comment by aaguiarz** [comment] 2023-03-29 17:33
Hey @tnipri 

Were you able to finally use OpenFGA? Would you mind emailing me at andres.aguiar at okta.com and share what has been your experience with it?

Thanks
