### ISSUE TITLE
Migration doesn't support --datastore-username and --datastore-password

### ISSUE THREAD

**Issue by martin31821** [openfga/openfga#1125] opened 2023-11-06 19:07 UTC
**Summary**

- Reproduction steps:
  1. running `openfga migrate` the same way as `openfga run`, namely with --datastore-username and --datastore-password set.
- What did you expect to happen?
  1. Expected migrations to work
- What actually happened?
  1. Migrations failed with `unknown flag: --datastore-password`

**OpenFGA version or commit**: v1.3.5 (via helm chart)

**Store data**

not relevant.

**Comment by jon-whit** [comment] 2023-11-06 20:05
@martin31821 the help message output for the `openfga migrate` command shows the following:

```
migrate -h
The migrate command is used to migrate the database schema needed for OpenFGA.

Usage:
  openfga migrate [flags]

Flags:
      --datastore-engine string   (required) the datastore engine that will be used for persistence
      --datastore-uri string      (required) the connection uri of the database to run the migrations against (e.g. 'postgres://postgres:password@localhost:5432/postgres')
  -h, --help                      help for migrate
      --timeout duration          a timeout for the time it takes the migrate process to connect to the database (default 1m0s)
      --verbose                   enable verbose migration logs (default false)
      --version uint              the version to migrate to (if omitted the latest schema will be used)
```

The `openfga migrate` command doesn't currently support overriding `datastore-username` and/or `datastore-password` like the `openfga run` entrypoint does. So the expectation is that you provide the credentials inline in the `datastore-uri`.

For that reason, I'm not marking this as a bug, because it's working as intended. However, if you feel this experience isn't ideal then we can consider marking this as an enhancement and looking into adding those similar flags/overrides in the `migrate` entrypoint as well 👍

**Comment by martin31821** [comment] 2023-11-06 20:25
@jon-whit I wanted to mark it as enhancement, and also contribute the respective code, just fyi. 

I'm trying to use it with the zalando postgres operator which writes the username and password into a k8s secret, so along with the small fixes in the helm chart, I felt like that would be the natural choice also for the migrate tool.

**Closed** 2023-11-20 19:41 UTC
Labels: enhancement
