### ISSUE TITLE
Usage of internal?

### ISSUE THREAD

**Issue by mxplusb** [openfga/openfga#871] opened 2023-07-14 22:46 UTC
There are a lot of core runtime packages for openfga under the `internal` path. Why are those packages there and not part of `pkg`? It seems to be the opposite of "open"

**Comment by rhamzeh** [comment] 2023-07-16 02:52
Hi @mxplusb 

In general we try to follow the [Go guidelines towards internal](https://go.dev/doc/go1.4#internalpackages), and try not to put too many things outside internal b/c we don't want people to assume that the interfaces are stable.

However if there are particular functionalities you'd like exposed, let us know and we can either move them out as is or work on an interface that we believe is more stable for external use. PRs are also always appreciated, but let us know what you are planning to do before spending the effort, just in case we have other options in mind.

**Comment by mxplusb** [comment] 2023-07-17 21:50
I’ve worked with Go for a long time and understand `internal`, thanks for the refreshers since it had been awhile 🙂

For my use case, I’m evaluating embedding OpenFGA in my [database](https://github.com/mxplusb/pleiades) so I can provide native FGA functionality at the lowest levels of data operations. The embedding would essentially be a complete rewrite of the OpenFGA runtime architecture to fit into my database’s runtime architecture, and I would also be providing my own storage implementation for the graph. I know I would be taking on a ton of ownership if I went that route, so I was looking through the OpenFGA code base and wanted to ask about the `internal` usages because it felt like stuff was inconsistently placed there.

Ory’s Zanzibar impl, Keto, puts almost everything in `internal` and that really took their implementation off the table for me. I like OpenFGA because it’s less of that, and it feels less “corporate” (even though I know there’s corporate backing for the project). Is y’all’s usage of `internal` focused on safe early iterations of unstable APIs, or is there a long-term plan for putting more stuff in it? If I decide to embed OpenFGA, would I risk losing access to the existing libraries in `pkg` in later releases? Should I create a one-time fork and then port updates to the internal libraries as needed?

Personally, partially because of Keto’s egregiously offensive usage of `internal`, I’m finding the landscape for FGA solutions is very limited, and embedding what exists is very risky. The only path forward for my use case is embedding because I can’t take an external dependency on another database cuz I’m building a database 🤷🏼‍♀️

Whatever y’all end up using `internal` for is, of course, up to y’all. If my use case is something y’all are interested in supporting, keeping very limited things in `internal` so I can consume OpenFGA exclusively as a library that would be super helpful. I’ll hard fork and port updates if my use case is out of scope, it’ll just be more effort for me. That being said, if there’s interest and alignment in supporting my use case, I’m happy to donate and maintain any authz schemas for my database as reference templates (once I get that far) to OpenFGA‘s code base.

Happy to answer questions y’all might have.

**Comment by mxplusb** [comment] 2023-07-17 22:15
> For example, we have a public contract with the server and storage and typesystem packages (among a few others), and this is because we need those imports in other projects. If another team were to want to embed OpenFGA as a library, then they would need the same imports from `pkg` but not from `internal`.

I missed this nuance before I replied, it’s pretty much exactly what I want to do! If you can keep everything but the CLI/server runtime code in `pkg`, that would be amazing. Personally, I’ll need the storage interface and the graph SDK as a starting point.

**Comment by jon-whit** [comment] 2023-07-17 22:32
> If you can keep everything but the CLI/server runtime code in pkg, that would be amazing. Personally, I’ll need the storage interface and the graph SDK as a starting point.

@mxplusb Our intent is for the `Server` to be imported if you need the RPCs to serve queries and write/read things. From the sounds of your use case, that should suffice, because it allows you to provide any implementation of the storage interface and it will allow you to embed it wherever you need in your Go app. We don't intend to have a public contract with the `interna/graph` package symbols at this time, and so if you are referring to that package and have a need for the deeply internal graph resolution code, then it's unlikely we'll make that public unless we have a compelling reason to do so.

Could you elaborate more about your use case and why you need access to the internal graph package?

**Comment by mxplusb** [comment] 2023-07-18 01:22
> Could you elaborate more about your use case and why you need access to the internal graph package?

Sure. I'm providing high-level details, but I'm not sure how much detail you want, so let me know if you have more questions.

My use case is to provide complex authz for a distributed, monolithic, multi-trillion key value store. The kv store itself has a relatively simplistic interface, but it's the platform for complex database storage structures, such as graphs with Gremlin, distributed SQL, RDF triple stores, and other complex data storage structures. To ensure the kv store platform can model complex authz relationships to support a complex set of data structures, I've identified FGA as a foundational technology to provide complex authz support. The requirements for embedding are fairly low: a storage interface which can be implemented, and the underlying graph library.

The storage interface is a requirement because the backend is not compatible with off-the-shelf solutions, and I can't take an external system dependency. The storage implementation is a sharded kv store so it can store the graph across multiple nodes in my kv store cluster. This allows the storage implementation to have centralized writes while having distributed yet linearizable reads, meeting the scalability requirements.

Direct access to the underlying graph library is needed because the app framework needs access to manage the lifecycle, manage the storage implementation, and operate the graph without exposing it to end users. By exposing the graph directly to users through RPC, it creates risks for data integrity/security/compliance, and I don't want to introduce that kind of risk.

Nearly all calls to the graph will be internal to each node as it will primarily be used to check kv store access on reads and writes - with trillions of keys the kv store can't make network hops or serializations on every read or write. Any RPCs for graph management that would be needed will be specific to the kv store, and the platform uses a mixture of HTTP/3 + QUIC.

---

I did dig deeper into the server structure to see what the opportunities are there. I did notice y'all separated the graph operations into `pkg/server/commands`. From what I can tell, that library is closest to being able to meet my requirements, but it relies heavily on checks, validations, and other bits and pieces from `pkg/server`, which takes a hard dependency on `internal/{gateway,graph,validation}`.

> We don't intend to have a public contract with the interna/graph package symbols at this time, and so if you are referring to that package and have a need for the deeply internal graph resolution code, then it's unlikely we'll make that public unless we have a compelling reason to do so.

That code is already public, it's just not available through `go get`. To say, _"it's unlikely that we'll make that public unless we have a compelling reason to do so"_ really sounds like it's not actually _OpenFGA_, but _PublicFGA_. Is this decision because there's actually too much instability in the API, or because it creates the risk other companies might create their own FGA offerings to compete with Auth0 & Okta using work from said companies' engineers & PMs?

If the real concern is there is real instability in the `internal` packages, then I would argue the instability be documented and versioned so devs can make their own choices. I'm happy to submit a PR to make those APIs public, and document any instabilities they might have for downstream consumers.

**Comment by jon-whit** [comment] 2023-07-18 16:19
@mxplusb thanks for the detailed overview. I've taken a couple of the excerpts and responded inline.

> The storage interface is a requirement because the backend is not compatible with off-the-shelf solutions, and I can't take an external system dependency. The storage implementation is a sharded kv store so it can store the graph across multiple nodes in my kv store cluster.

Awesome, that shouldn't be an issue. You can implement the `OpenFGADatastore` interface in `pkg/storage` for your kv store in a way that meets your requirements for consistency, latency, and availability.

> Direct access to the underlying graph library is needed because the app framework needs access to manage the lifecycle, manage the storage implementation, and operate the graph without exposing it to end users. By exposing the graph directly to users through RPC, it creates risks for data integrity/security/compliance, and I don't want to introduce that kind of risk.

Gotcha. If you embed the OpenFGA Server (e.g. `pkg/server`) in your application, you don't have to expose the RPCs of the OpenFGA server structure to users. You can delegate calls to the RPC stubs of the server without exposing them publicly in any way. Let's pretend you're implementing a server for your application and you have a public HTTP handler.. The following code demonstrates how you can use the OpenFGA server embedded without exposing any of the underlying OpenFGA RPC queries to the end user:

```go
type MXPlusBServer struct {
    openfga *openfga.Server
}

func (s *MXPlusBServer) SomeHTTPHandler(w http.ResponseWriter, r *http.Request) {
    
    checkResponse, err := s.openfga.Check(r.Context(), &openfgapb.CheckRequest{...})
    if err != nil {
        // handle error
        w.Write([]byte("internal error"))
        w.WriteHeader(http.StatusInternalServerError)
        return
    }

    if checkResponse.GetAllowed() {
        // request is authorized, do something
       return
    }

    w.Write([]byte("unauthorized"))
    w.WriteHeader(http.StatusUnauthorized)
}
```
and you can construct the OpenFGA server with your custom storage implementation. For example:
```go
import (
    openfgastore "github.com/openfga/openfga/pkg/storage"
    openfga "github.com/openfga/openfga/server"
)

var mxplusbKvStore openfgastore.OpenFGADatastore

openfgaServer := openfga.New(
    &openfga.Dependencies{Datastore: mxplusbKvStore, ...},
    &openfga.Config{...},
)
```

> Nearly all calls to the graph will be internal to each node as it will primarily be used to check kv store access on reads and writes - with trillions of keys the kv store can't make network hops or serializations on every read or write. Any RPCs for graph management that would be needed will be specific to the kv store, and the platform uses a mixture of HTTP/3 + QUIC.

If I understand this correctly you're saying that you cannot afford to use the OpenFGA server RPCs because of the overhead of serialization to/from the storage layer as you resolve the graph query and the network hops to/from the storage layer is also not acceptable on every read/write? In which case, what is the plan for evaluating the graph with persistent data?

> That code is already public, it's just not available through go get. To say, "it's unlikely that we'll make that public unless we have a compelling reason to do so" really sounds like it's not actually OpenFGA, but PublicFGA. Is this decision because there's actually too much instability in the API, or because it creates the risk other companies might create their own FGA offerings to compete with Auth0 & Okta using work from said companies' engineers & PMs?

I think this is a matter of personal perception.. If code is publicly available on the internet and carries with it a permissive license (e.g. Apache 2.0), that to me it is highly open (from a legal perspective). You can create derivative works off it without almost any hassle given the permissiveness of Apache 2.0. To say that source code inside of an `internal` package is not "open" is a misrepresentation of the permissive nature of Apache 2.0 licensed software. The code may not be importable, but that is _by design_, and this is for the same reason that other developers make use of features of other languages for package scoping (e.g. in Java we have `private/protected/public`). If we don't intend to have symbols publicly consumable, that is not because we are trying to protect ourselves from competition in the market (otherwise we wouldn't make it publicly available on the internet 😄 ), but that is because we don't see a strong use case for making it public and we don't want the internet to build contracts on it if we do not intend to maintain said contracts.  Hyrum's law says

> With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.

We're trying to reduce that blast radius by using package scoping mechanisms like so many other languages do. That's all.

There are handfuls of open-source projects that no one would argue are not "open" and they make use of the `internal` package pattern. Here are a few examples:
* https://github.com/goreleaser/goreleaser
* https://github.com/traefik/traefik
* https://github.com/redis/go-redis
etc..

Again, we're open to the idea of moving any code out of `internal` into `pkg`, but we just want to see more community reasons to do so before we go making something a public part of our API contract. And before we move anything from `internal` to `pkg` we'd probably want to do our due diligence to cleanup the interfaces etc.. 

Could we schedule a quick call to discuss further? It may help to get in person.

**Comment by mxplusb** [comment] 2023-07-18 17:18
> If you embed the OpenFGA Server (e.g. pkg/server) in your application, you don't have to expose the RPCs of the OpenFGA server structure to users. You can delegate calls to the RPC stubs of the server without exposing them publicly in any way.

Is your implementation of `pkg/server.Server` not bundled with a network implementation? It looked like it was but maybe I misunderstood the architecture. If it's not bundled with a network implementation, it very well might meet my needs. I want to bring my own storage and skip the networking, so as long as your server implementation lets me do that, then it might be sufficient.

> If I understand this correctly you're saying that you cannot afford to use the OpenFGA server RPCs because of the overhead of serialization to/from the storage layer as you resolve the graph query and the network hops to/from the storage layer is also not acceptable on every read/write?

Not quite. The generic flow is `{Get,Put}KeyHandler -> GlobalKeyStore -> ReplicationEngine -> LocalNodeKeyStore -> {Get,Put}KeyFromStorage`. I'm wanting to introduce OpenFGA between `{Get,Put}KeyHandler` and `GlobalKeyStore` so authz can be verified before there's network roundtripping or data storage operations.  

Because this is a hot path for data operations, I'm not able to do is make an external network request, even an RPC call, to an external system between `GetKeyHandler` and `GlobalKeyStore`. An external network request introduces unnecessary overhead and it creates an external dependency. But, if your `pkg/server.Server` implementation doesn't require networking, then I'll definitely take a look!

> In which case, what is the plan for evaluating the graph with persistent data?

Can you clarify the question? I'm not following, sorry. Are you asking about performance impacts for trying to resolve the relationships of {m,b,tr}illions of keys?

> Hyrum's law says

Fair point.

> Again, we're open to the idea of moving any code out of internal into pkg, but we just want to see more community reasons to do so before we go making something a public part of our API contract. And before we move anything from internal to pkg we'd probably want to do our due diligence to cleanup the interfaces etc..

Another fair point.

> Could we schedule a quick call to discuss further?

If you'd like. My email is in my bio (not gonna paste it cuz bots), I'm generally available most days after 3p MT.

**Comment by jon-whit** [comment] 2023-07-18 17:36
@mxplusb 

> Is your implementation of pkg/server.Server not bundled with a network implementation? It looked like it was but maybe I misunderstood the architecture. If it's not bundled with a network implementation, it very well might meet my needs. I want to bring my own storage and skip the networking, so as long as your server implementation lets me do that, then it might be sufficient.

The only network involved in the RPC stubs is if the storage layer involves network. If you pass in a storage implementation to the `Server` struct that does not do any network hops, then no network will be involved. A good example of this is our `memory` storage adapter in `pkg/storage/memory`. For example

```go
import (
  openfga "github.com/openfga/openfga/pkg/server"
  openfgamem "github.com/openfga/openfga/pkg/storage/memory"
)

openfgaServer := openfga.New(
  &openfga.Dependencies{Datastore: openfgamem.New(...), ...},
  &openfga.Config{...},
)

result, err := openfgaServer.Check(...) // no network is used since we're using the memory storage adapter
```

**Comment by mxplusb** [comment] 2023-07-18 18:01
Ahhhh that was the part I didn't know, thank you for helping me get there!

I will experiment with it and provide some feedback.

**Comment by miparnisari** [comment] 2023-07-18 20:55
Note that in the next release, the syntax will be simplified to

```go
openfgaServer := openfga.NewServerWithOpts(
	openfga.WithDatastore(datastore),
)
```

`datastore` is the only required parameter, everything else will be optional.

**Comment by jon-whit** [comment] 2023-07-19 22:28
@mxplusb I'm going to close for now as it seems we have a path forward. If you find otherwise, please feel free to reach back out and we can re-open and setup a call etc.. 👍

**Closed** 2023-07-19 22:28 UTC

**Comment by miparnisari** [comment] 2023-07-20 18:41
> Ahhhh that was the part I didn't know, thank you for helping me get there!

We should document in the readme or somewhere in the docs that this project can also be used as a library without the networking baggage

**Comment by miparnisari** [comment] 2023-08-16 19:15
Actually, right now, you shouldn't use the project as a library because you will lose the validation layer that is currently implemented as a server middleware 😬

**Comment by mxplusb** [comment] 2023-08-20 22:20
Thank you for the head's up!!
