### ISSUE TITLE
side effect of contextual tuple

### ISSUE THREAD

**Issue by mango009** [openfga/openfga#304] opened 2022-10-23 19:04 UTC
There are two issues of contextual tuple I discovered. Below is my model:

```
type user
type repository
  relations
    define admin as self
    define user as self
type group
  relations
    define member as self
type tenure
  relations
    define user as self
type artifact
  relations
    define allowed_tenure as self
    define can_download as user from repo and member from group
    define can_upload as can_download and user from allowed_tenure
    define group as self
    define repo as self
```

And I populate the model with the following relation:

```json
{
  "tuple_key": {
    "user": "user:anne",
    "relation": "member",
    "object": "group:engineering"
  }
}

{
  "tuple_key": {
    "user": "user:anne",
    "relation": "user",
    "object": "repository:us-east"
  }
}

{
  "tuple_key": {
    "user": "group:engineering",
    "relation": "group",
    "object": "artifact:doc1"
  }
}

{
  "tuple_key": {
    "user": "repository:us-east",
    "relation": "repo",
    "object": "artifact:doc1"
  }
}

{
  "tuple_key": {
    "user": "tenure:gt3",
    "relation": "allowed_tenure",
    "object": "artifact:doc1"
  }
}
```

It's apparent that `user:anne` has a `can_download` relation with `artifact:doc1`. And this can be verified with a `check` API. However, if I add a contextual tuple to the request in the body:

```
{
  "tuple_key": {
    "user": "anne",
    "relation": "can_download",
    "object": "artifact:doc1"
  },
  "contextual_tuples": {
    "tuple_keys": [
      {
        "user": "user:anne",
        "relation": "user",
        "object": "tenure:gt3"
      }
    ]
  }
}
```
The returned response is `false`. Is this an undesirable side effect of contextual tuple?

Another question is that I found that contextual tuple does not really work. The returned answer to a `can_upload` query is still false with the following request:

```
{
  "tuple_key": {
    "user": "anne",
    "relation": "can_upload",
    "object": "artifact:doc1"
  },
  "contextual_tuples": {
    "tuple_keys": [
      {
        "user": "user:anne",
        "relation": "user",
        "object": "tenure:gt3"
      }
    ]
  }
}
```

**Comment by rhamzeh** [comment] 2022-10-24 04:36
Hi @mango009 👋🏽 

1. Did you verify that your checks are working without the contextual tuples? I tried to check them here and they were (correctly) returning false.

The reason they are returning false is that in the checks you are forgetting the `user` type. It should be:

```json
{
  "tuple_key": {
    "user": "user:anne",
    "relation": "can_upload",
    "object": "artifact:doc1"
  }
}
```

Tried reproducing on the FGA Playground: https://play.fga.dev/stores/create/?id=01GG41ZGQZD6GMDBM84RK2FG49

```sh
curl -X POST 'https://api.playground.fga.dev/stores/01GG41ZGQZD6GMDBM84RK2FG49/check' \
 -d '{
  "tuple_key": {
    "user": "user:anne",
    "relation": "can_download",
    "object": "artifact:doc1"
  },
  "contextual_tuples": {
    "tuple_keys": [
      {
        "user": "user:anne",
        "relation": "user",
        "object": "tenure:gt3"
      }
    ]
  }
}'
```
returns `{"allowed":true,"resolution":""}` - which is correct. This would return the same result if the contextual tuple was not sent as placement in a tenure should not affect ability to download (according to the model).

```sh
curl -X POST 'https://api.playground.fga.dev/stores/01GG41ZGQZD6GMDBM84RK2FG49/check' \
 -d '{
  "tuple_key": {
    "user": "user:anne",
    "relation": "can_upload",
    "object": "artifact:doc1"
  },
  "contextual_tuples": {
    "tuple_keys": [
      {
        "user": "user:anne",
        "relation": "user",
        "object": "tenure:gt3"
      }
    ]
  }
}'
```
returns `{"allowed":true,"resolution":""}` - which is correct. This is different from if the contextual tuple was not passed, as if `user:anne` was not in that tenure, then they would not have had upload access.

Note: Unfortunately the Playground does not support intersections in the Graph preview.

**Comment by craigpastro** [comment] 2022-12-02 01:47
I'll close this issue for now. Please reopen it if it has not solved your problem.

**Closed by craigpastro** 2022-12-02 01:47 UTC
Labels: invalid

**Comment by aaguiarz** [comment] 2023-03-30 02:02
Hi @mango009 

Have you been able to successfully utilize OpenFGA? If so, I would love to hear about your experience and any feedback you may have.

If you don't mind sharing, please email me directly at andres.aguiar at openfga.dev

Thanks!
