### ISSUE TITLE
Partial successful writes or deletes

### ISSUE THREAD

**Issue by ragaeeb** [openfga/openfga#562] opened 2023-02-20 20:20 UTC
👋 Hello, is there any configuration we can set to do a "best-effort" for the tuples for `writes` or `deletes`?

For example, if I have the following:
```
{
   deletes: {
      tuple_keys: [...] // 20 items
   },
   writes: {
      tuple_keys: [...] // 20 items
   },
}
```

Imagine just `1` of the items in the `deletes` array does not exist, or just `1` of the items in the `writes` array has a duplicate already in the server, the entire request would fail, and there is no easy to way to differentiate what was the issue from the error message thrown in regards to what index. If both a tuple in the `deletes` does not exist AND the one in the `writes` already exists, then it would only throw an error message for one of them, so even if we implemented a retry logic the OpenFGA server would throw again.

Is it possible to have some sort of 'best-effort' solution where it will silently fail on any errors (ie: ignore any delete tuples that don't exist, or ignore any duplicate tuples that we try to write)?

**Comment by rhamzeh** [comment] 2023-02-23 14:42
Thanks for the request @ragaeeb.

That is something we are considering.

We've discussed this a bit in openfga/openfga#258, and we decided to offer it as part of the SDKs as a first step while we consider its viability to be supported at the API layer.

Our main thought process is documented here: https://github.com/openfga/openfga/issues/258#issuecomment-1338157050

For now, closing this as a duplicate of the original to centralize the discussion, but please feel free to add your comments there!

**Closed by rhamzeh** 2023-02-23 14:42 UTC
Labels: enhancement
